#!/usr/bin/env bash
# Bash script that prints "Best School" 20 times  that display diffrent thing in 4,9,17 loop
a=1;
while [ $a -lt 21 ];
do
    echo "$a"
    case $a in
        4)
            echo "bad luck from China";;
        9)
            echo "bad luck from Japan";;
        17)
            echo "bad luck from Italy";;
    esac
    ((a++));
done;
